name: Mark stale issues and pull requestrs

on:
  schedule:
  - cron: "0 16 * * 1-5"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This is stale'
        stale-issue-label: 'stale'
        days-before-stale: 1
        days-before-close: 1
