on:
  schedule:
  - cron: 00 15 * * 1-5
name: Risk Standup Weekly Action
jobs:
  cycle-weekly-meeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: cycle-weekly-meeting
      uses: ./weekly-meeting
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
